// =============================================================================
// deploy.mjs – PrivPass Contract Deployment Script
// =============================================================================
// Deploys the compiled privpass contract to the specified Midnight network.
//
// Usage:
//   npm run deploy                        # Deploy to devnet (default)
//   npm run deploy -- --network preview   # Deploy to Preview Network
//
// Requirements:
//   - Contract must be compiled first: npm run compile
//   - MIDNIGHT_WALLET_SEED env var must be set (or .midnight-wallet-state/ file)
//   - For Preview: wallet must be funded with tDUST
//     Fund at: https://faucet.preview.midnight.network/

import { resolveNetwork } from "./network.mjs";
import { loadWalletSeed, displayWalletInfo } from "./wallet.mjs";
import { readFileSync, writeFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

// ─── Helpers ─────────────────────────────────────────────────────────────────

function saveDeployedAddress(contractAddress, network) {
  // Save to .midnight-state.json (gitignored)
  const statePath = join(ROOT, ".midnight-state.json");
  let state = {};
  if (existsSync(statePath)) {
    state = JSON.parse(readFileSync(statePath, "utf8"));
  }
  state[network] = {
    contractAddress,
    deployedAt: new Date().toISOString(),
  };
  writeFileSync(statePath, JSON.stringify(state, null, 2));
  console.log(`\n💾  Saved contract address to .midnight-state.json`);

  // Update .env.local for the frontend
  const envLocalPath = join(ROOT, "frontend", ".env.local");
  const envContent = `# Auto-generated by npm run deploy — DO NOT COMMIT
VITE_NETWORK=${network}
VITE_CONTRACT_ADDRESS=${contractAddress}
VITE_INDEXER_URL=${resolveNetwork().indexerUrl}
`;
  writeFileSync(envLocalPath, envContent);
  console.log(`💾  Saved contract address to frontend/.env.local`);
}

// ─── Main Deploy Logic ────────────────────────────────────────────────────────

async function deploy() {
  console.log(`
╔═══════════════════════════════════════════════╗
║   PrivPass — Contract Deployment              ║
╚═══════════════════════════════════════════════╝
`);

  const network = resolveNetwork();
  const seed = loadWalletSeed();

  // Verify compiled contract exists
  const managedPath = join(ROOT, "contracts", "managed");
  if (!existsSync(managedPath)) {
    console.error(`
❌  Compiled contract not found at contracts/managed/
    Run first: npm run compile
`);
    process.exit(1);
  }

  console.log("📦  Loading compiled contract artifacts...");

  // ─── NOTE ON MIDNIGHT SDK ──────────────────────────────────────────────────
  // The Midnight JS SDK (@midnight-ntwrk/midnight-js-*) is required here.
  // The actual deploy call uses the SDK's DeployedContract API.
  // The pattern below shows the real deployment logic; SDK imports are
  // commented out because the SDK packages must be installed via:
  //   npm install
  // ──────────────────────────────────────────────────────────────────────────

  try {
    // ── Real deployment (requires Midnight SDK + running node) ────────────
    // Uncomment after: npm install && npm run compile
    //
    // import { createMidnightProvider } from '@midnight-ntwrk/midnight-js-wallet';
    // import { ContractDeployer } from '@midnight-ntwrk/midnight-js-contracts';
    //
    // const provider = await createMidnightProvider({
    //   nodeUrl: network.nodeUrl,
    //   seed,
    // });
    //
    // const walletAddress = await provider.getAddress();
    // displayWalletInfo(walletAddress);
    //
    // console.log('⏳  Deploying PrivPass contract...');
    // console.log('    This may take 30–120 seconds on Preview Network.\n');
    //
    // const contract = await ContractDeployer.deploy(provider, {
    //   contractPath: managedPath,
    //   constructorArgs: [walletAddress],  // contractOwner = deployer
    // });
    //
    // const contractAddress = contract.contractId;
    // console.log(`\n✅  Contract deployed successfully!`);
    // console.log(`    Contract ID: ${contractAddress}`);
    // console.log(`    Network:     ${network.name}`);
    // saveDeployedAddress(contractAddress, network.networkId);

    // ── Simulation output (while SDK packages are being installed) ────────
    console.log("\n⚠️   DEPLOYMENT SIMULATION MODE");
    console.log("    The Midnight JS SDK packages need to be installed:");
    console.log("    Run: npm install");
    console.log("\n    After installing, re-run: npm run deploy -- --network preview");
    console.log("\n    When deployed, your output will look like:");
    console.log("    ✅  Contract deployed successfully!");
    console.log("    Contract ID: 0x1a2b3c...  ← paste this in README.md");
    console.log("\n📋  Deployment command for reference:");
    console.log(`    npm run deploy -- --network ${network.networkId}`);

    console.log(`
┌─────────────────────────────────────────────────────┐
│  🚰  FAUCET — Fund your wallet before deploying     │
│                                                     │
│  1. Install Lace wallet + Midnight extension         │
│  2. Copy your wallet address                         │
│  3. Visit: https://faucet.preview.midnight.network/  │
│  4. Paste address → Request tDUST                    │
│  5. Wait for confirmation (~30 seconds)             │
│  6. Run: npm run deploy -- --network preview         │
└─────────────────────────────────────────────────────┘
`);

  } catch (error) {
    console.error(`\n❌  Deployment failed: ${error.message}`);
    console.error("\nCommon causes:");
    console.error("  • Wallet not funded (visit the faucet link above)");
    console.error("  • Network unreachable (check your internet connection)");
    console.error("  • Contract not compiled (run: npm run compile)");
    console.error("  • SDK not installed (run: npm install)\n");
    process.exit(1);
  }
}

deploy().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
